import React from 'react'
import Head from 'next/head'
import { FC } from 'react'
import { Navbar } from '../ui/Navbar';
interface Props {

}
export const MainPage:FC = ({children}) => {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    <main>
        {children}
    </main>
</>
  )
}

export default MainPage